# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            DayDream
tagline:          'A shy pig'
description:      'A blog just for fun. '
url:              http://dewhao.github.io

author:
  name:           'dewhao'
  url:            https://twitter.com/dewhao

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/dewhao
